# Generated by Django 5.2 on 2026-03-13 19:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('can_reapply', models.BooleanField(default=False)),
                ('current_employer', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=100)),
                ('years_experience', models.PositiveIntegerField(help_text='Total years of industry experience')),
                ('project_types_worked', models.TextField(help_text='Types of projects worked (pipeline, facility, civil, etc.)')),
                ('industry_background', models.TextField(help_text='Describe your industry background and experience')),
                ('certifications_held', models.TextField(blank=True, help_text='Any current certifications (CWI, NACE, PMP, etc.)')),
                ('additional_info', models.TextField(blank=True, help_text='Anything else you want us to know')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes — never shown to applicant')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
