# Generated by Django 5.2 on 2026-03-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_project_type_user_project_types_and_more'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='current_employer',
        ),
        migrations.RemoveField(
            model_name='application',
            name='industry_background',
        ),
        migrations.RemoveField(
            model_name='application',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='application',
            name='project_types_worked',
        ),
        migrations.RemoveField(
            model_name='application',
            name='years_experience',
        ),
        migrations.AddField(
            model_name='application',
            name='work_history',
            field=models.ManyToManyField(blank=True, help_text='Work history entries submitted with this application', related_name='applications', to='accounts.workhistory'),
        ),
    ]
