# Generated by Django 5.2 on 2025-04-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fdq_level',
            field=models.CharField(blank=True, choices=[('L1', 'FDQ Level 1 - Practitioner'), ('L2', 'FDQ Level 2 - Implementer')], max_length=2, null=True, verbose_name='FDQ Certification Level'),
        ),
    ]
