# Generated by Django 5.2 on 2026-03-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_fdq_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='certified_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fdq_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_certified',
        ),
        migrations.AddField(
            model_name='user',
            name='certifications_held',
            field=models.TextField(blank=True, help_text='Comma-separated list of certifications (e.g. CWI, NACE, PMP)'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='project_type',
            field=models.CharField(blank=True, choices=[('pipeline', 'Pipeline'), ('facility', 'Facility / Plant'), ('commercial', 'Commercial Building'), ('infrastructure', 'Infrastructure / Civil'), ('residential', 'Residential'), ('industrial', 'Industrial / Manufacturing'), ('other', 'Other')], help_text='Primary project type', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of industry experience', null=True),
        ),
    ]
