# Generated by Django 5.2 on 2026-03-13 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_certified_at_remove_user_fdq_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='project_type',
        ),
        migrations.AddField(
            model_name='user',
            name='project_types',
            field=models.TextField(blank=True, help_text='Comma-separated list of project types'),
        ),
        migrations.AlterField(
            model_name='user',
            name='certifications_held',
            field=models.TextField(blank=True, help_text='Comma-separated list from predefined options'),
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('position_name', models.CharField(max_length=100)),
                ('industry', models.CharField(choices=[('gc', 'General Contractor'), ('insp', 'Inspection'), ('owner', 'Owner/Client'), ('sub', 'Subcontractor / Service Provider'), ('fab', 'Fabrication'), ('coat', 'Coating/Painting'), ('equip', 'Equipment Supplier / Rental'), ('consult', 'Consultant / Engineering'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_position', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_current', '-start_date'],
            },
        ),
    ]
