# Generated by Django 5.2 on 2025-04-18 19:51

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_banner_image_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='summary',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
