# Generated by Django 5.2 on 2026-03-13 23:28

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Rich text content for reading lessons.'),
        ),
    ]
