# Generated by Django 5.2 on 2026-03-15 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_lesson_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('reading', 'Reading'), ('video', 'Video'), ('interactive', 'Interactive')], default='reading', max_length=15),
        ),
        migrations.CreateModel(
            name='InteractiveExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(max_length=50)),
                ('config', models.JSONField()),
                ('passing_score', models.IntegerField(default=80)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='lms.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=1)),
                ('score', models.IntegerField()),
                ('passed', models.BooleanField()),
                ('attempt_number', models.IntegerField(default=1)),
                ('response_data', models.JSONField(default=dict)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lms.interactiveexercise')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
    ]
