# Generated by Django 5.2 on 2026-03-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_lesson_content_type_interactiveexercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='gate_required',
            field=models.BooleanField(default=False, help_text='If True, the student must pass the interactive exercise at the end of this module before the next module unlocks.'),
        ),
    ]
